default_config:

# Example configuration.yaml entry
input_number:
  weight:
    name: Weight
    initial: 70
    min: 10
    max: 200
    step: 0.1
  impedance:
    name: Impedance
    initial: 400
    min: 0
    max: 3000
    step: 1

template:
  - sensor:
      - name: Weight
        state: "{{ states('input_number.weight') }}"
        unit_of_measurement: "kg"
      - name: Impedance
        state: "{{ states('input_number.impedance') }}"
        unit_of_measurement: "ohm"

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
#   wait: true
